Repository aws/serverless-application-model, pull requests merged in 2021-06, with the labels that each got.

#2046 test: New test group to test for side effects
  tests/translator/input/api_with_usageplans_shared_no_side_effect_1.yaml
  tests/translator/input/api_with_usageplans_shared_no_side_effect_2.yaml
  tests/translator/output/api_with_usageplans_shared_no_side_effect_1.json
  tests/translator/output/api_with_usageplans_shared_no_side_effect_2.json
  tests/translator/output/aws-cn/api_with_usageplans_shared_no_side_effect_1.json
  tests/translator/output/aws-cn/api_with_usageplans_shared_no_side_effect_2.json
  tests/translator/output/aws-us-gov/api_with_usageplans_shared_no_side_effect_1.json
  tests/translator/output/aws-us-gov/api_with_usageplans_shared_no_side_effect_2.json
  tests/translator/test_translator.py
Labels: pr/internal, stage/approved

#2045 docs: fix dead link (develop)
  docs/safe_lambda_deployments.rst
Labels: area/docs, pr/internal, stage/approved

#1952 Percentage-based Enablement for Feature Toggle
  samtranslator/feature_toggle/dialup.py
  samtranslator/feature_toggle/feature_toggle.py
  samtranslator/translator/translator.py
  tests/feature_toggle/input/feature_toggle_config.json
  tests/feature_toggle/test_dialup.py
  tests/feature_toggle/test_feature_toggle.py
Labels: pr/internal

#2062 Adding support for metric publishing, manually tested and tests pending.
  Makefile
  integration/metrics/__init__.py
  integration/metrics/test_metrics_integration.py
  samtranslator/metrics/__init__.py
  samtranslator/metrics/metrics.py
  samtranslator/translator/translator.py
  tests/metrics/test_metrics.py
Labels: pr/internal

#2026 feat: Add ValidateBody/ValidateParameters attribute to setup API model validators
  samtranslator/model/eventsources/push.py
  samtranslator/swagger/swagger.py
  tests/swagger/test_swagger.py
  tests/translator/input/api_request_model_with_validator.yaml
  tests/translator/input/api_request_model_with_validator_openapi_3.yaml
  tests/translator/input/error_api_request_model_with_intrinsics_validator.yaml
  tests/translator/input/error_api_request_model_with_strings_validator.yaml
  tests/translator/output/api_request_model_with_validator.json
  tests/translator/output/api_request_model_with_validator_openapi_3.json
  tests/translator/output/aws-cn/api_request_model_with_validator.json
  tests/translator/output/aws-cn/api_request_model_with_validator_openapi_3.json
  tests/translator/output/aws-us-gov/api_request_model_with_validator.json
  tests/translator/output/aws-us-gov/api_request_model_with_validator_openapi_3.json
  tests/translator/output/error_api_request_model_with_intrinsics_validator.json
  tests/translator/output/error_api_request_model_with_strings_validator.json
  tests/translator/test_translator.py
Labels: area/apigateway, area/resource/api, pr/external

#2074 fix: fail with invalid resource, when RetentionPolicy has unresolved intrinsic value
  samtranslator/model/sam_resources.py
  tests/translator/input/basic_layer.yaml
  tests/translator/input/error_layer_invalid_properties.yaml
  tests/translator/output/aws-cn/basic_layer.json
  tests/translator/output/aws-us-gov/basic_layer.json
  tests/translator/output/basic_layer.json
  tests/translator/output/error_layer_invalid_properties.json
Labels: pr/internal
