Repository aws/serverless-application-model, pull requests merged in 2021-09, with the labels that each got.

#2108 fix: handle string RestApiId in Api event source swagger integration
  samtranslator/model/api/api_generator.py
  samtranslator/model/eventsources/push.py
  samtranslator/model/stepfunctions/events.py
  samtranslator/plugins/api/implicit_api_plugin.py
  samtranslator/swagger/swagger.py
  samtranslator/translator/translator.py
  tests/swagger/test_swagger.py
  tests/translator/input/api_swagger_integration_with_ref_intrinsic_api_id.yaml
  tests/translator/input/api_swagger_integration_with_string_api_id.yaml
  tests/translator/input/error_api_swagger_integration_with_condition_intrinsic_api_id.yaml
  tests/translator/input/error_api_swagger_integration_with_find_in_map_intrinsic_api_id.yaml
  tests/translator/input/error_api_swagger_integration_with_getatt_intrinsic_api_id.yaml
  tests/translator/input/error_api_swagger_integration_with_join_intrinsic_api_id.yaml
  tests/translator/input/error_api_swagger_integration_with_select_intrinsic_api_id.yaml
  tests/translator/input/error_api_swagger_integration_with_sub_intrinsic_api_id.yaml
  tests/translator/input/error_api_swagger_integration_with_transform_intrinsic_api_id.yaml
  tests/translator/output/api_swagger_integration_with_ref_intrinsic_api_id.json
  tests/translator/output/api_swagger_integration_with_string_api_id.json
  tests/translator/output/aws-cn/api_swagger_integration_with_ref_intrinsic_api_id.json
  tests/translator/output/aws-cn/api_swagger_integration_with_string_api_id.json
  tests/translator/output/aws-us-gov/api_swagger_integration_with_ref_intrinsic_api_id.json
  tests/translator/output/aws-us-gov/api_swagger_integration_with_string_api_id.json
  tests/translator/output/error_api_swagger_integration_with_condition_intrinsic_api_id.json
  tests/translator/output/error_api_swagger_integration_with_find_in_map_intrinsic_api_id.json
  tests/translator/output/error_api_swagger_integration_with_getatt_intrinsic_api_id.json
  tests/translator/output/error_api_swagger_integration_with_join_intrinsic_api_id.json
  tests/translator/output/error_api_swagger_integration_with_select_intrinsic_api_id.json
  tests/translator/output/error_api_swagger_integration_with_sub_intrinsic_api_id.json
  tests/translator/output/error_api_swagger_integration_with_transform_intrinsic_api_id.json
  tests/translator/test_translator.py
Labels: area/resource/api, pr/internal

#1839 Update capitalisation of 'GitHub' within Markdown files
  .github/ISSUE_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: pr/external

#2041 fix: Allow multiple path segments in BasePath
  samtranslator/model/api/http_api_generator.py
  tests/model/api/test_http_api_generator.py
Labels: pr/external, area/apigateway
