Repository aws/serverless-application-model, pull requests merged in 2021-12, with the labels that each got.

#2252 fix: Check type of resource type is a string
  samtranslator/model/__init__.py
  tests/translator/input/resource_with_invalid_type.yaml
  tests/translator/output/aws-cn/resource_with_invalid_type.json
  tests/translator/output/aws-us-gov/resource_with_invalid_type.json
  tests/translator/output/resource_with_invalid_type.json
  tests/translator/test_translator.py
Labels: pr/internal

#2262 fix: open api set_path_default_authorizer (#2248)
  samtranslator/open_api/open_api.py
  tests/translator/input/http_api_multiple_authorizers.yaml
  tests/translator/output/aws-cn/http_api_multiple_authorizers.json
  tests/translator/output/aws-us-gov/http_api_multiple_authorizers.json
  tests/translator/output/http_api_multiple_authorizers.json
  tests/translator/test_translator.py
Labels: pr/internal

#2240 Do not abort SAR loop on throttling
  samtranslator/plugins/application/serverless_app_plugin.py
  tests/plugins/application/test_serverless_app_plugin.py
Labels: pr/internal, maintainer/need-followup

#2272 Fixing DisableExecuteApiEndpoint property for REST and adding integ t…
  samtranslator/model/api/api_generator.py
  tests/translator/input/api_with_disable_api_execute_endpoint.yaml
  tests/translator/output/api_with_disable_api_execute_endpoint.json
  tests/translator/output/aws-cn/api_with_disable_api_execute_endpoint.json
  tests/translator/output/aws-us-gov/api_with_disable_api_execute_endpoint.json
  tests/translator/test_translator.py
Labels: pr/external
