Repository aws/serverless-application-model, pull requests merged in 2022-10, with the labels that each got.

#2527 chore: rerun failing tests
  pytest.ini
  requirements/dev.txt
Labels: pr/internal

#2531 docs: update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr/internal

#2535 chore: run tests with GitHub workflow
  .github/workflows/build.yml
Labels: pr/internal

#2538 chore: pylint fix
  .pylintrc
  samtranslator/feature_toggle/feature_toggle.py
  samtranslator/intrinsics/actions.py
  samtranslator/intrinsics/resource_refs.py
  samtranslator/metrics/metrics.py
  samtranslator/model/__init__.py
  samtranslator/model/api/api_generator.py
  samtranslator/model/api/http_api_generator.py
  samtranslator/model/eventsources/pull.py
  samtranslator/model/eventsources/push.py
  samtranslator/model/preferences/deployment_preference.py
  samtranslator/model/preferences/deployment_preference_collection.py
  samtranslator/model/role_utils/role_constructor.py
  samtranslator/model/sam_resources.py
  samtranslator/model/sns.py
  samtranslator/model/stepfunctions/events.py
  samtranslator/model/stepfunctions/generators.py
  samtranslator/model/stepfunctions/resources.py
  samtranslator/open_api/open_api.py
  samtranslator/parser/parser.py
  samtranslator/plugins/__init__.py
  samtranslator/plugins/api/implicit_api_plugin.py
  samtranslator/plugins/application/serverless_app_plugin.py
  samtranslator/plugins/globals/globals.py
  samtranslator/policy_template_processor/exceptions.py
  samtranslator/policy_template_processor/template.py
  samtranslator/public/exceptions.py
  samtranslator/public/intrinsics.py
  samtranslator/public/models.py
  samtranslator/public/open_api.py
  samtranslator/public/parser.py
  samtranslator/public/plugins.py
  samtranslator/public/sdk/parameter.py
  samtranslator/public/sdk/resource.py
  samtranslator/public/sdk/template.py
  samtranslator/public/swagger.py
  samtranslator/public/translator.py
  samtranslator/swagger/swagger.py
  samtranslator/translator/translator.py
  samtranslator/utils/py27hash_fix.py
  samtranslator/validator/validator.py
Labels: pr/external, stage/needs-triage

#2539 chore: remove AppVeyor
  README.md
  appveyor-integration-test.yml
  appveyor.yml
  tox.ini
Labels: pr/internal

#2543 Add Integration Test Deployer Logging Improvements
  integration/helpers/deployer/deployer.py
Labels: pr/internal

#2540 Upgrade Pylint Version and Fix Pylint Issues
  .pylintrc
  integration/helpers/deployer/utils/artifact_exporter.py
  requirements/dev.txt
  samtranslator/feature_toggle/feature_toggle.py
  samtranslator/metrics/method_decorator.py
  samtranslator/model/connector_profiles/profile.py
  samtranslator/model/preferences/deployment_preference_collection.py
  samtranslator/plugins/application/serverless_app_plugin.py
  samtranslator/policy_template_processor/processor.py
  samtranslator/swagger/swagger.py
  samtranslator/validator/validator.py
  tests/policy_template_processor/test_processor.py
Labels: pr/external, stage/needs-triage

#2524 Add ability to set State of EventBridge Rule
  samtranslator/model/stepfunctions/events.py
  samtranslator/validator/sam_schema/schema.json
  tests/model/eventsources/test_eventbridge_rule_source.py
  tests/model/stepfunctions/test_eventbridge_rule_source.py
  tests/translator/input/eventbridgerule_with_dlq.yaml
  tests/translator/input/state_machine_with_cwe.yaml
  tests/translator/output/aws-cn/eventbridgerule_with_dlq.json
  tests/translator/output/aws-cn/state_machine_with_cwe.json
  tests/translator/output/aws-us-gov/eventbridgerule_with_dlq.json
  tests/translator/output/aws-us-gov/state_machine_with_cwe.json
  tests/translator/output/eventbridgerule_with_dlq.json
  tests/translator/output/state_machine_with_cwe.json
Labels: pr/external, stage/needs-triage

#2545 Add Integ Test Skip Flag for EventBus
  integration/helpers/resource.py
Labels: pr/internal

#2544 chore: Enable more pylint rules and fixes pylint issues
  .pylintrc
  samtranslator/model/api/api_generator.py
  samtranslator/model/api/http_api_generator.py
  samtranslator/model/sam_resources.py
  samtranslator/model/stepfunctions/generators.py
  samtranslator/plugins/application/serverless_app_plugin.py
  samtranslator/swagger/swagger.py
  samtranslator/translator/logical_id_generator.py
  samtranslator/translator/translator.py
Labels: pr/external, stage/needs-triage

#2541 chore: add CodeQL
  .github/workflows/codeql.yml
Labels: pr/internal

#2547 Enable more pylint rules and fixes pylint issues
  .pylintrc
  samtranslator/intrinsics/actions.py
  samtranslator/intrinsics/resolver.py
  samtranslator/intrinsics/resource_refs.py
  samtranslator/model/__init__.py
  samtranslator/model/api/api_generator.py
  samtranslator/model/architecture.py
  samtranslator/model/connector/connector.py
  samtranslator/model/connector_profiles/profile.py
  samtranslator/model/intrinsics.py
  samtranslator/model/preferences/deployment_preference_collection.py
  samtranslator/model/s3_utils/uri_parser.py
  samtranslator/model/sam_resources.py
  samtranslator/open_api/open_api.py
  samtranslator/plugins/globals/globals.py
  samtranslator/swagger/swagger.py
  samtranslator/translator/translator.py
Labels: pr/external, stage/needs-triage

#2549 fix: Correct kafka property names in generated event source mapping
  samtranslator/model/eventsources/pull.py
  samtranslator/model/lambda_.py
  tests/translator/output/aws-cn/function_with_msk.json
  tests/translator/output/aws-cn/function_with_msk_with_intrinsics.json
  tests/translator/output/aws-cn/function_with_self_managed_kafka.json
  tests/translator/output/aws-cn/self_managed_kafka_with_intrinsics.json
  tests/translator/output/aws-us-gov/function_with_msk.json
  tests/translator/output/aws-us-gov/function_with_msk_with_intrinsics.json
  tests/translator/output/aws-us-gov/function_with_self_managed_kafka.json
  tests/translator/output/aws-us-gov/self_managed_kafka_with_intrinsics.json
  tests/translator/output/function_with_msk.json
  tests/translator/output/function_with_msk_with_intrinsics.json
  tests/translator/output/function_with_self_managed_kafka.json
  tests/translator/output/self_managed_kafka_with_intrinsics.json
Labels: pr/internal

#2548 Enable more pylint rules and fixes pylint issues
  .pylintrc
  samtranslator/intrinsics/resolver.py
  samtranslator/model/__init__.py
  samtranslator/model/api/api_generator.py
  samtranslator/model/apigatewayv2.py
  samtranslator/model/eventsources/push.py
  samtranslator/model/function_policies.py
  samtranslator/plugins/globals/globals.py
  tests/model/test_function_policies.py
Labels: pr/external, maintainer/need-followup, stage/needs-triage

#2551 chore: Add transform test creation script
  DEVELOPMENT_GUIDE.md
  Makefile
  bin/add_transform_test.py
Labels: pr/external, stage/needs-triage

#2554 Do not change input file and exit if hardcoded partition used
  bin/add_transform_test.py
Labels: pr/external, stage/needs-triage

#2537 feat: replace `DependsOn` to connector by its generated logical IDs
  samtranslator/model/connector/connector.py
  samtranslator/model/sam_resources.py
  samtranslator/utils/utils.py
  tests/translator/input/connector_bucket_to_function.yaml
  tests/translator/input/connector_dependson_replace.yaml
  tests/translator/output/aws-cn/connector_dependson_replace.json
  tests/translator/output/aws-us-gov/connector_dependson_replace.json
  tests/translator/output/connector_dependson_replace.json
  tests/utils/test_utils.py
Labels: pr/internal

#2559 chore: use connector logical ID for DependsOn in integ test
  integration/resources/templates/combination/connector_bucket_to_function_write.yaml
Labels: pr/internal

#2560 Bug fix: Fix DisableExecuteApiEndpoint bug fix
  Makefile
  integration/combination/test_api_with_disable_execute_api_endpoint.py
  integration/resources/expected/combination/api_with_disable_execute_api_endpoint_openapi_3.json
  integration/resources/templates/combination/api_with_disable_execute_api_endpoint_openapi_3.yaml
  samtranslator/model/api/api_generator.py
  samtranslator/model/apigateway.py
  samtranslator/open_api/open_api.py
  samtranslator/plugins/api/implicit_api_plugin.py
  samtranslator/plugins/globals/globals.py
  samtranslator/swagger/swagger.py
  samtranslator/utils/py27hash_fix.py
  tests/translator/input/api_with_disable_api_execute_endpoint_openapi_3.yaml
  tests/translator/output/api_with_disable_api_execute_endpoint_openapi_3.json
  tests/translator/output/aws-cn/api_with_disable_api_execute_endpoint_openapi_3.json
  tests/translator/output/aws-us-gov/api_with_disable_api_execute_endpoint_openapi_3.json
Labels: pr/external, stage/needs-triage

#2525 Add ability to set Name of EventBridge Rule
  samtranslator/model/eventsources/push.py
  samtranslator/model/stepfunctions/events.py
  samtranslator/validator/sam_schema/schema.json
  tests/model/eventsources/test_eventbridge_rule_source.py
  tests/model/stepfunctions/test_eventbridge_rule_source.py
  tests/translator/input/eventbridgerule_with_dlq.yaml
  tests/translator/input/state_machine_with_cwe.yaml
  tests/translator/output/aws-cn/eventbridgerule_with_dlq.json
  tests/translator/output/aws-cn/state_machine_with_cwe.json
  tests/translator/output/aws-us-gov/eventbridgerule_with_dlq.json
  tests/translator/output/aws-us-gov/state_machine_with_cwe.json
  tests/translator/output/eventbridgerule_with_dlq.json
  tests/translator/output/state_machine_with_cwe.json
Labels: pr/external, maintainer/need-followup, stage/needs-triage

#2555 Remove unrecognized pylint options
  .pylintrc
Labels: pr/external, stage/needs-triage

#2562 chore: Make PropertyType and related validator typed
  samtranslator/model/__init__.py
  samtranslator/model/apigateway.py
  samtranslator/model/apigatewayv2.py
  samtranslator/model/cloudformation.py
  samtranslator/model/codedeploy.py
  samtranslator/model/cognito.py
  samtranslator/model/dynamodb.py
  samtranslator/model/events.py
  samtranslator/model/eventsources/cloudwatchlogs.py
  samtranslator/model/eventsources/pull.py
  samtranslator/model/eventsources/push.py
  samtranslator/model/iam.py
  samtranslator/model/iot.py
  samtranslator/model/lambda_.py
  samtranslator/model/log.py
  samtranslator/model/route53.py
  samtranslator/model/s3.py
  samtranslator/model/sam_resources.py
  samtranslator/model/sns.py
  samtranslator/model/sqs.py
  samtranslator/model/stepfunctions/events.py
  samtranslator/model/stepfunctions/resources.py
  samtranslator/model/types.py
  samtranslator/sdk/resource.py
Labels: pr/internal

#2563 chore: Make intrinsics helper functions typed
  samtranslator/model/api/api_generator.py
  samtranslator/model/api/http_api_generator.py
  samtranslator/model/apigateway.py
  samtranslator/model/apigatewayv2.py
  samtranslator/model/cloudformation.py
  samtranslator/model/codedeploy.py
  samtranslator/model/cognito.py
  samtranslator/model/connector/connector.py
  samtranslator/model/dynamodb.py
  samtranslator/model/events.py
  samtranslator/model/eventsources/cloudwatchlogs.py
  samtranslator/model/eventsources/pull.py
  samtranslator/model/eventsources/push.py
  samtranslator/model/iam.py
  samtranslator/model/intrinsics.py
  samtranslator/model/iot.py
  samtranslator/model/lambda_.py
  samtranslator/model/log.py
  samtranslator/model/preferences/deployment_preference_collection.py
  samtranslator/model/resource_policies.py
  samtranslator/model/role_utils/role_constructor.py
  samtranslator/model/s3.py
  samtranslator/model/sam_resources.py
  samtranslator/model/sns.py
  samtranslator/model/sqs.py
  samtranslator/model/stepfunctions/events.py
  samtranslator/model/stepfunctions/generators.py
  samtranslator/model/stepfunctions/resources.py
  samtranslator/model/update_policy.py
  samtranslator/open_api/open_api.py
  samtranslator/plugins/api/implicit_api_plugin.py
  samtranslator/plugins/api/implicit_http_api_plugin.py
  samtranslator/plugins/policies/policy_templates_plugin.py
  samtranslator/swagger/swagger.py
Labels: pr/internal

#2564 chore: Type improvements initiated from adding __all__
  bin/sam-translate.py
  samtranslator/feature_toggle/feature_toggle.py
  samtranslator/intrinsics/actions.py
  samtranslator/intrinsics/resolver.py
  samtranslator/intrinsics/resource_refs.py
  samtranslator/metrics/metrics.py
  samtranslator/model/__init__.py
  samtranslator/model/api/api_generator.py
  samtranslator/model/api/http_api_generator.py
  samtranslator/model/apigateway.py
  samtranslator/model/apigatewayv2.py
  samtranslator/model/eventbridge_utils.py
  samtranslator/model/eventsources/cloudwatchlogs.py
  samtranslator/model/eventsources/pull.py
  samtranslator/model/eventsources/push.py
  samtranslator/model/exceptions.py
  samtranslator/model/iam.py
  samtranslator/model/preferences/deployment_preference.py
  samtranslator/model/preferences/deployment_preference_collection.py
  samtranslator/model/resource_policies.py
  samtranslator/model/role_utils/__init__.py
  samtranslator/model/role_utils/role_constructor.py
  samtranslator/model/s3_utils/uri_parser.py
  samtranslator/model/sam_resources.py
  samtranslator/model/stepfunctions/__init__.py
  samtranslator/model/stepfunctions/events.py
  samtranslator/model/stepfunctions/generators.py
  samtranslator/model/stepfunctions/resources.py
  samtranslator/open_api/open_api.py
  samtranslator/parser/parser.py
  samtranslator/plugins/__init__.py
  samtranslator/plugins/api/default_definition_body_plugin.py
  samtranslator/plugins/api/implicit_api_plugin.py
  samtranslator/plugins/api/implicit_http_api_plugin.py
  samtranslator/plugins/api/implicit_rest_api_plugin.py
  samtranslator/plugins/application/serverless_app_plugin.py
  samtranslator/plugins/globals/globals.py
  samtranslator/plugins/globals/globals_plugin.py
  samtranslator/plugins/policies/policy_templates_plugin.py
  samtranslator/policy_template_processor/template.py
  samtranslator/public/exceptions.py
  samtranslator/public/intrinsics.py
  samtranslator/public/open_api.py
  samtranslator/public/plugins.py
  samtranslator/public/sdk/resource.py
  samtranslator/public/sdk/template.py
  samtranslator/public/swagger.py
  samtranslator/public/translator.py
  samtranslator/sdk/resource.py
  samtranslator/sdk/template.py
  samtranslator/swagger/swagger.py
  samtranslator/translator/transform.py
  samtranslator/translator/translator.py
  samtranslator/utils/py27hash_fix.py
Labels: pr/internal

#2567 feat: Add support to Fn::GetAtt X.Y when looking up IAM role in serve…
  samtranslator/model/intrinsics.py
  tests/test_intrinsics.py
  tests/translator/input/connector_sfn_to_sfn.yaml
  tests/translator/output/aws-cn/connector_sfn_to_sfn.json
  tests/translator/output/aws-us-gov/connector_sfn_to_sfn.json
  tests/translator/output/connector_sfn_to_sfn.json
Labels: pr/internal

#2565 docs: new README
  README.md
Labels: pr/internal

#2569 docs: use `sam sync` instead of `sam deploy`
  README.md
Labels: pr/internal

#2571 docs: add SAM workshop, minor polish to README
  README.md
Labels: pr/internal

#2573 chore: add Gitpod config, docs polish
  .gitpod.yml
  DEVELOPMENT_GUIDE.md
Labels: pr/internal
