Repository aws/serverless-application-model, pull requests merged in 2022-11, with the labels that each got.

#2574 Bug fix: Fix generated Lambda permission's SourceARN when $default path is used in HTTP API
  integration/combination/test_function_with_http_api.py
  integration/resources/expected/combination/function_with_http_api_default_path.json
  integration/resources/templates/combination/function_with_http_api_default_path.yaml
  samtranslator/model/eventsources/push.py
  tests/translator/input/explicit_http_api_default_path.yaml
  tests/translator/output/aws-cn/explicit_http_api_default_path.json
  tests/translator/output/aws-us-gov/explicit_http_api_default_path.json
  tests/translator/output/explicit_http_api_default_path.json
Labels: pr/external, stage/needs-triage

#2520 Better test for type of a variable
  samtranslator/model/eventsources/pull.py
Labels: pr/external, maintainer/need-response, stage/needs-triage

#2580 chore: clean up docs
  docs/cloudformation_compatibility.rst
  docs/conf.py
  docs/get-started-youtube.png
  docs/index.rst
  docs/internals/generated_resources.rst
  docs/internals/index.rst
Labels: pr/internal

#2582 docs: development guidelines
  DEVELOPMENT_GUIDE.md
Labels: pr/internal

#2584 docs: add "add types" guideline
  DEVELOPMENT_GUIDE.md
Labels: pr/internal

#2585 chore: add development guidelines to checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr/internal

#2583 RedrivePolicy added
  samtranslator/model/eventsources/push.py
  samtranslator/model/sns.py
  tests/model/eventsources/test_sns_event_source.py
Labels: pr/internal

#2586 chore: Type improvements in http api generator
  samtranslator/feature_toggle/feature_toggle.py
  samtranslator/metrics/method_decorator.py
  samtranslator/model/__init__.py
  samtranslator/model/api/api_generator.py
  samtranslator/model/api/http_api_generator.py
  samtranslator/model/apigateway.py
  samtranslator/model/apigatewayv2.py
  samtranslator/model/eventsources/cloudwatchlogs.py
  samtranslator/model/eventsources/pull.py
  samtranslator/model/eventsources/push.py
  samtranslator/model/eventsources/scheduler.py
  samtranslator/model/route53.py
  samtranslator/model/s3_utils/uri_parser.py
  samtranslator/model/sam_resources.py
  samtranslator/model/stepfunctions/events.py
  samtranslator/model/stepfunctions/generators.py
  samtranslator/model/tags/resource_tagging.py
  samtranslator/open_api/open_api.py
  samtranslator/plugins/api/default_definition_body_plugin.py
  samtranslator/plugins/api/implicit_api_plugin.py
  samtranslator/plugins/application/serverless_app_plugin.py
  samtranslator/plugins/globals/globals_plugin.py
  samtranslator/plugins/policies/policy_templates_plugin.py
  samtranslator/translator/logical_id_generator.py
  samtranslator/translator/managed_policy_translator.py
  samtranslator/utils/types.py
  tests/translator/output/error_httpapi_mtls_configuration_invalid_type.json
Labels: pr/internal

#2593 ci: Allow build workflow to be triggered manually or by gh-cli
  .github/workflows/build.yml
Labels: pr/internal

#2591 feat: add `UnescapeMappingTemplate` to state machine `Api` event
  integration/helpers/base_test.py
  integration/resources/expected/single/state_machine_with_api.json
  integration/resources/templates/single/state_machine_with_api.yaml
  integration/single/test_basic_api.py
  samtranslator/model/__init__.py
  samtranslator/model/stepfunctions/events.py
  tests/translator/input/error_state_machine_with_api_intrinsics.yaml
  tests/translator/input/state_machine_with_api.yaml
  tests/translator/output/aws-cn/state_machine_with_api.json
  tests/translator/output/aws-us-gov/state_machine_with_api.json
  tests/translator/output/error_state_machine_with_api_intrinsics.json
  tests/translator/output/state_machine_with_api.json
Labels: pr/internal

#2594 chore: Type improvements in sam_resources.py
  samtranslator/feature_toggle/dialup.py
  samtranslator/feature_toggle/feature_toggle.py
  samtranslator/intrinsics/resolver.py
  samtranslator/model/__init__.py
  samtranslator/model/api/api_generator.py
  samtranslator/model/api/http_api_generator.py
  samtranslator/model/eventbridge_utils.py
  samtranslator/model/eventsources/pull.py
  samtranslator/model/eventsources/push.py
  samtranslator/model/eventsources/scheduler.py
  samtranslator/model/preferences/deployment_preference_collection.py
  samtranslator/model/sam_resources.py
  samtranslator/model/stepfunctions/events.py
  samtranslator/model/update_policy.py
  samtranslator/policy_template_processor/template.py
Labels: pr/internal

#2595 fix: correct URL suffix
  integration/resources/templates/single/state_machine_with_api.yaml
Labels: pr/internal

#2592 chore: Add CODEOWNERS file
  CODEOWNERS
Labels: pr/internal

#2596 docs: mention `Property` vs `PropertyType`
  DEVELOPMENT_GUIDE.md
Labels: pr/internal

#2597 chore: Prevent bin/ from installed as a package
  setup.py
Labels: pr/internal

#2598 chore: Add --add-test-metadata option to yaml formatter
  bin/_file_formatter.py
  bin/json-format.py
  bin/yaml-format.py
Labels: pr/internal

#2492 feat: Support "Name" for AWS::Serverless::HttpApi
  samtranslator/model/api/http_api_generator.py
  samtranslator/model/sam_resources.py
  samtranslator/open_api/open_api.py
  tests/model/api/test_http_api_generator.py
  tests/translator/input/explicit_http_api_with_name.yaml
  tests/translator/output/aws-cn/explicit_http_api_with_name.json
  tests/translator/output/aws-us-gov/explicit_http_api_with_name.json
  tests/translator/output/explicit_http_api_with_name.json
  tests/translator/test_translator.py
Labels: pr/internal

#2602 docs: mention `PassThroughProperty`
  DEVELOPMENT_GUIDE.md
Labels: pr/internal

#2603 fix: Raise correct exception when Api authorizer identity is not a dict
  samtranslator/model/apigateway.py
  tests/translator/input/error_api_authorizer_property_indentity_with_invalid_type.yaml
  tests/translator/output/error_api_authorizer_property_indentity_with_invalid_type.json
Labels: pr/internal

#2607 fix: Raise correct exception when !Sub variable value (Parameter.Default) is not string
  samtranslator/intrinsics/actions.py
  tests/translator/input/error_intrinsic_sub_with_list.yaml
  tests/translator/output/error_intrinsic_sub_with_list.json
Labels: pr/internal

#2608 fix: Raise correct exception when FunctionUrlConfig.Cors is not dict
  samtranslator/model/sam_resources.py
  tests/translator/input/error_function_with_function_url_config_with_invalid_cors_parameter.yaml
  tests/translator/output/error_function_with_function_url_config_with_invalid_cors_parameter.json
Labels: pr/internal

#2609 fix: Raise correct exception when swagger: securityDefinitions is not dict
  samtranslator/swagger/swagger.py
  tests/translator/input/error_swagger_security_definitions_not_dict.yaml
  tests/translator/output/error_swagger_security_definitions_not_dict.json
Labels: pr/internal

#2610 fix: Raise correct exception when swagger: responses.headers is not a dict
  samtranslator/model/api/api_generator.py
  samtranslator/swagger/swagger.py
  tests/translator/input/error_api_invalid_openapi_path_with_invalid_responses.yaml
  tests/translator/output/error_api_invalid_openapi_path_with_invalid_responses.json
Labels: pr/internal

#2611 fix: Raise correct exception when api authorizer is not a dict
  samtranslator/swagger/swagger.py
  tests/translator/input/error_api_invalid_auth.yaml
  tests/translator/output/error_api_invalid_auth.json
Labels: pr/internal

#2604 fix: KeyError: u'AWS_IAM' and add typing
  samtranslator/model/api/api_generator.py
  samtranslator/model/api/http_api_generator.py
  samtranslator/open_api/open_api.py
  samtranslator/swagger/swagger.py
  tests/translator/input/api_http_with_default_iam_authorizer.yaml
  tests/translator/output/api_http_with_default_iam_authorizer.json
  tests/translator/output/aws-cn/api_http_with_default_iam_authorizer.json
  tests/translator/output/aws-us-gov/api_http_with_default_iam_authorizer.json
Labels: pr/internal, pr/external, stage/needs-triage

#2605 adding support for all SSM Parameters types
  samtranslator/validator/sam_schema/definitions/parameter.json
  tests/validator/input/root/error_minimal_template_with_parameters.yaml
  tests/validator/input/root/success_minimal_template_with_parameters.yaml
  tests/validator/output/root/error_minimal_template_with_parameters.json
Labels: pr/external, stage/needs-triage

#2613 fix: Raise correct exception when restapi authorizer is not a dict
  samtranslator/open_api/open_api.py
  tests/translator/input/error_api_invalid_auth.yaml
  tests/translator/output/error_api_invalid_auth.json
Labels: pr/internal

#2614 fix: Raise correct exception when kafka SourceAccessConfigurations is not a list
  samtranslator/model/eventsources/pull.py
  tests/translator/input/error_invalid_self_managed_kafka_config.yaml
  tests/translator/output/error_invalid_self_managed_kafka_config.json
Labels: pr/internal

#2616 feat: initial JSON schema
  Makefile
  bin/validate.sh
  requirements/dev.txt
  samtranslator/schema/schema.json
  samtranslator/schema/schema.py
Labels: pr/internal

#2618 chore: add schema types for Connector and SimpleTable
  samtranslator/schema/schema.json
  samtranslator/schema/schema.py
Labels: pr/internal

#2619 chore: add schema types to Application
  samtranslator/schema/schema.json
  samtranslator/schema/schema.py
Labels: pr/internal

#2620 chore: add schema types to LayerVersion
  samtranslator/schema/schema.json
  samtranslator/schema/schema.py
Labels: pr/internal

#2615 fix: Handle when openapi/swagger security property is null
  samtranslator/open_api/open_api.py
  samtranslator/swagger/swagger.py
  tests/translator/input/error_api_invalid_security.yaml
  tests/translator/input/error_swagger_security_not_dict.yaml
  tests/translator/output/error_api_invalid_security.json
Labels: pr/internal

#2621 chore: Experiment on unitify property value validation messages
  samtranslator/model/api/api_generator.py
  samtranslator/model/api/http_api_generator.py
  samtranslator/model/apigateway.py
  samtranslator/model/apigatewayv2.py
  samtranslator/model/sam_resources.py
  samtranslator/plugins/application/serverless_app_plugin.py
  samtranslator/validator/value_validator.py
  tests/translator/output/error_api_authorizer_property_indentity_header_with_invalid_type.json
  tests/translator/output/error_api_authorizer_property_indentity_with_invalid_type.json
  tests/translator/output/error_api_with_custom_domains_route53_invalid_type.json
  tests/translator/output/error_application_properties.json
  tests/translator/output/error_function_with_function_url_config_with_invalid_cors_parameter.json
  tests/translator/output/error_function_with_invalid_dlq_property_type.json
  tests/translator/output/error_null_application_id.json
  tests/translator/output/error_table_primary_key_missing_name.json
  tests/translator/output/error_table_primary_key_missing_type.json
Labels: pr/internal

#2622 fix: Raise correct exception when Api.Domain is not a map
  samtranslator/model/api/api_generator.py
  samtranslator/schema/__init__.py
  samtranslator/schema/schema.py
  tests/translator/input/error_api_with_custom_domains_invalid.yaml
  tests/translator/output/error_api_with_custom_domains_invalid.json
Labels: pr/internal

#2624 feat: fast schema validation
  Makefile
  bin/validate.sh
  bin/validate_schema.py
Labels: pr/internal

#2625 chore: add state machine events schema skeleton
  bin/validate_schema.py
  samtranslator/schema/schema.json
  samtranslator/schema/schema.py
Labels: pr/internal

#2626 Maintainer list update: Add GavinZZ and Aayush and Connor
  .github/workflows/pr-labeler.yml
Labels: pr/internal, pr/external, stage/needs-triage

#2627 fix: Raise correct exception when Identity.Headers is not of valid type
  samtranslator/model/apigateway.py
  tests/translator/input/error_api_authorizer_property_indentity_with_invalid_type.yaml
  tests/translator/output/error_api_authorizer_property_indentity_with_invalid_type.json
Labels: pr/internal

#2628 chore: add state machine schema types
  bin/validate_schema.py
  samtranslator/schema/schema.json
  samtranslator/schema/schema.py
Labels: pr/internal

#2623 Add Schema Type to AWS::Serverless::Lambda
  bin/validate_schema.py
  samtranslator/schema/schema.json
  samtranslator/schema/schema.py
  tests/translator/input/api_with_method_aws_iam_auth.yaml
  tests/translator/input/eventbridgerule_with_retry_policy.yaml
  tests/translator/input/function_with_disabled_traffic_hook.yaml
  tests/translator/output/api_with_method_aws_iam_auth.json
  tests/translator/output/aws-cn/api_with_method_aws_iam_auth.json
  tests/translator/output/aws-cn/eventbridgerule_with_retry_policy.json
  tests/translator/output/aws-cn/function_with_disabled_traffic_hook.json
  tests/translator/output/aws-us-gov/api_with_method_aws_iam_auth.json
  tests/translator/output/aws-us-gov/eventbridgerule_with_retry_policy.json
  tests/translator/output/aws-us-gov/function_with_disabled_traffic_hook.json
  tests/translator/output/eventbridgerule_with_retry_policy.json
  tests/translator/output/function_with_disabled_traffic_hook.json
Labels: pr/internal, pr/external, stage/needs-triage

#2629 Skeleton Lambda Events Schema
  bin/validate_schema.py
  samtranslator/schema/schema.json
  samtranslator/schema/schema.py
Labels: pr/internal

#2630 fix: Raise correct exception when httpapi event RouteSettings is not dict
  samtranslator/open_api/open_api.py
  samtranslator/plugins/api/implicit_http_api_plugin.py
  samtranslator/plugins/api/implicit_rest_api_plugin.py
  samtranslator/sdk/resource.py
  samtranslator/sdk/template.py
  samtranslator/validator/value_validator.py
  tests/translator/input/error_http_api_event_invalid_api.yaml
  tests/translator/output/error_http_api_event_invalid_api.json
Labels: pr/internal

#2633 fix: Raise correct exception when event OnFailure is not of valid type
  samtranslator/model/eventsources/pull.py
  samtranslator/validator/value_validator.py
  tests/translator/input/error_function_with_invalid_event_destination_config.yaml
  tests/translator/output/aws-cn/error_function_with_missing_on_failure_in_stream_event_destination_config.json
  tests/translator/output/aws-us-gov/error_function_with_missing_on_failure_in_stream_event_destination_config.json
  tests/translator/output/error_function_with_invalid_event_destination_config.json
  tests/translator/output/error_function_with_missing_on_failure_in_stream_event_destination_config.json
Labels: pr/internal

#2634 chore: add HttpApi schema
  samtranslator/schema/schema.json
  samtranslator/schema/schema.py
Labels: pr/internal

#2636 fix: Raise correct exception when DefaultAuthorizer is not of valid type
  samtranslator/model/api/http_api_generator.py
  tests/translator/input/error_api_invalid_auth.yaml
  tests/translator/input/error_default_authorizer_should_be_string_in_api.yaml
  tests/translator/output/error_api_invalid_auth.json
  tests/translator/output/error_default_authorizer_should_be_string_in_api.json
Labels: pr/internal

#2635 Add detailed type to AWS::Serverless::Lambda Schema
  bin/validate_schema.py
  samtranslator/schema/schema.json
  samtranslator/schema/schema.py
Labels: pr/internal

#2637 fix: Raise correct exception when some properties are not dict when used with .get()
  samtranslator/model/eventsources/pull.py
  samtranslator/model/eventsources/push.py
  samtranslator/open_api/open_api.py
  tests/translator/output/error_s3_lambda_configuration_invalid_type.json
Labels: pr/internal

#2606 Create SAM StateMachine without providing a role or policy
  integration/combination/test_connectors.py
  integration/resources/expected/combination/connector_sfn_to_function_without_policy.json
  integration/resources/templates/combination/connector_sfn_to_function_without_policy.yaml
  samtranslator/model/stepfunctions/generators.py
  tests/model/stepfunctions/test_state_machine_generator.py
  tests/translator/input/connector_sfn_to_function_without_policy.yaml
  tests/translator/output/aws-cn/connector_sfn_to_function_without_policy.json
  tests/translator/output/aws-us-gov/connector_sfn_to_function_without_policy.json
  tests/translator/output/connector_sfn_to_function_without_policy.json
Labels: pr/internal, pr/external, stage/needs-triage

#2638 Add detailed type to AWS::Serverless::Api schema
  bin/validate_schema.py
  samtranslator/schema/schema.json
  samtranslator/schema/schema.py
Labels: pr/internal

#2639 chore: refactor schema
  .coveragerc
  samtranslator/model/api/api_generator.py
  samtranslator/schema/any_cfn_resource.py
  samtranslator/schema/aws_serverless_api.py
  samtranslator/schema/aws_serverless_application.py
  samtranslator/schema/aws_serverless_connector.py
  samtranslator/schema/aws_serverless_function.py
  samtranslator/schema/aws_serverless_httpapi.py
  samtranslator/schema/aws_serverless_layerversion.py
  samtranslator/schema/aws_serverless_simpletable.py
  samtranslator/schema/aws_serverless_statemachine.py
  samtranslator/schema/common.py
  samtranslator/schema/schema.json
  samtranslator/schema/schema.py
Labels: pr/internal

#2641 Add schema types to global section
  bin/validate_schema.py
  samtranslator/schema/aws_serverless_api.py
  samtranslator/schema/aws_serverless_function.py
  samtranslator/schema/aws_serverless_httpapi.py
  samtranslator/schema/aws_serverless_simpletable.py
  samtranslator/schema/schema.json
Labels: pr/internal

#2644 chore: scaffolding for schema docs
  samtranslator/schema/aws_serverless_function.py
  samtranslator/schema/common.py
  samtranslator/schema/docs.yaml
  samtranslator/schema/schema.json
  samtranslator/schema/schema.py
Labels: pr/internal

#2643 Validate schema as unit test
  Makefile
  bin/validate_schema.py
  tests/schema/__init__.py
  tests/schema/test_validate_schema.py
  tests/translator/input/error_schema_validation_wrong_property.yaml
  tests/translator/input/error_schema_validation_wrong_type.yaml
  tests/translator/output/error_schema_validation_wrong_property.json
  tests/translator/output/error_schema_validation_wrong_type.json
Labels: pr/internal

#2646 fix: Raise correct exception when some properties are not dict when used dict methods
  samtranslator/model/api/api_generator.py
  samtranslator/model/api/http_api_generator.py
  samtranslator/model/apigateway.py
  samtranslator/swagger/swagger.py
Labels: pr/internal

#2650 chore: Add connect timeout to serverlessrepo clients
  samtranslator/feature_toggle/feature_toggle.py
  samtranslator/plugins/application/serverless_app_plugin.py
  samtranslator/utils/constants.py
Labels: pr/internal

#2649 Fix wrong types for schema
  samtranslator/schema/aws_serverless_api.py
  samtranslator/schema/aws_serverless_function.py
  samtranslator/schema/schema.json
  tests/schema/test_validate_schema.py
Labels: pr/internal

#2652 feat: more docs scaffolding + `AWS::Serverless::Function`
  bin/parse_docs.py
  samtranslator/schema/aws_serverless_function.py
  samtranslator/schema/common.py
  samtranslator/schema/docs.json
  samtranslator/schema/docs.yaml
  samtranslator/schema/schema.json
  tests/translator/input/function_with_function_url_config_with_intrinsics.yaml
Labels: pr/internal

#2654 chore: docs to Connector/Application/LayerVersion/SimpleTable
  samtranslator/schema/aws_serverless_application.py
  samtranslator/schema/aws_serverless_connector.py
  samtranslator/schema/aws_serverless_layerversion.py
  samtranslator/schema/aws_serverless_simpletable.py
  samtranslator/schema/schema.json
  tests/translator/input/function_with_function_url_config_with_intrinsics.yaml
Labels: pr/internal

#2655 chore: add schema docs to `AWS::Serverless::Api`
  samtranslator/schema/aws_serverless_api.py
  samtranslator/schema/schema.json
Labels: pr/internal

#2656 chore: add docs for Function event Type/Properties
  samtranslator/schema/aws_serverless_function.py
  samtranslator/schema/schema.json
Labels: pr/internal

#2658 add schema docs to AWS::Serverless::HttpApi
  samtranslator/schema/aws_serverless_httpapi.py
  samtranslator/schema/schema.json
Labels: pr/internal

#2657 chore: add schema docs to AWS::Serverless::StateMachine
  samtranslator/schema/aws_serverless_statemachine.py
  samtranslator/schema/schema.json
Labels: pr/internal

#2647 Multi dest connector
  integration/combination/test_connectors.py
  integration/resources/expected/combination/connector_event_rule_to_lambda_write_multiple.json
  integration/resources/expected/combination/connector_function_to_bucket_read_multiple.json
  integration/resources/expected/combination/connector_mix_destination.json
  integration/resources/templates/combination/connector_event_rule_to_lambda_write_multiple.yaml
  integration/resources/templates/combination/connector_function_to_bucket_read_multiple.yaml
  integration/resources/templates/combination/connector_mix_destination.yaml
  samtranslator/model/sam_resources.py
  samtranslator/schema/aws_serverless_connector.py
  samtranslator/schema/schema.json
  tests/model/test_sam_resources.py
  tests/translator/input/connector_api_to_multiple_function.yaml
  tests/translator/input/connector_function_to_multiple_s3.yaml
  tests/translator/input/connector_mix_destination.yaml
  tests/translator/input/connector_rule_to_multiple_sns.yaml
  tests/translator/input/connector_sqs_to_multiple_function.yaml
  tests/translator/input/error_connector.yaml
  tests/translator/output/aws-cn/connector_api_to_multiple_function.json
  tests/translator/output/aws-cn/connector_function_to_multiple_s3.json
  tests/translator/output/aws-cn/connector_mix_destination.json
  tests/translator/output/aws-cn/connector_rule_to_multiple_sns.json
  tests/translator/output/aws-cn/connector_sqs_to_multiple_function.json
  tests/translator/output/aws-us-gov/connector_api_to_multiple_function.json
  tests/translator/output/aws-us-gov/connector_function_to_multiple_s3.json
  tests/translator/output/aws-us-gov/connector_mix_destination.json
  tests/translator/output/aws-us-gov/connector_rule_to_multiple_sns.json
  tests/translator/output/aws-us-gov/connector_sqs_to_multiple_function.json
  tests/translator/output/connector_api_to_multiple_function.json
  tests/translator/output/connector_function_to_multiple_s3.json
  tests/translator/output/connector_mix_destination.json
  tests/translator/output/connector_rule_to_multiple_sns.json
  tests/translator/output/connector_sqs_to_multiple_function.json
  tests/translator/output/error_connector.json
Labels: pr/internal

#2659 feat: Role Path for AWS::Serverless::Function
  docs/globals.rst
  integration/resources/expected/single/function_with_role_path.json
  integration/resources/templates/single/function_with_role_path.yaml
  integration/single/test_basic_function.py
  samtranslator/model/role_utils/role_constructor.py
  samtranslator/model/sam_resources.py
  samtranslator/plugins/globals/globals.py
  samtranslator/schema/aws_serverless_function.py
  samtranslator/schema/schema.json
  tests/translator/input/function_with_globals_role_path.yaml
  tests/translator/input/function_with_role_and_role_path.yaml
  tests/translator/input/function_with_role_path.yaml
  tests/translator/output/aws-cn/function_with_globals_role_path.json
  tests/translator/output/aws-cn/function_with_role_and_role_path.json
  tests/translator/output/aws-cn/function_with_role_path.json
  tests/translator/output/aws-us-gov/function_with_globals_role_path.json
  tests/translator/output/aws-us-gov/function_with_role_and_role_path.json
  tests/translator/output/aws-us-gov/function_with_role_path.json
  tests/translator/output/error_globals_unsupported_property.json
  tests/translator/output/function_with_globals_role_path.json
  tests/translator/output/function_with_role_and_role_path.json
  tests/translator/output/function_with_role_path.json
Labels: pr/internal

#2663 chore: add JSON schema version
  samtranslator/schema/schema.json
  samtranslator/schema/schema.py
Labels: pr/internal

#2668 chore: remove feature request issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
Labels: pr/internal

#2669 docs: update contribution guidelines for feature requests
  CONTRIBUTING.md
Labels: pr/internal

#2648 chore: Refactor some chained dict.get() with dict_deep_get()
  samtranslator/model/api/api_generator.py
  samtranslator/model/api/http_api_generator.py
  samtranslator/open_api/open_api.py
  samtranslator/utils/utils.py
  tests/translator/input/error_api_invalid_openapi_path_with_empty_responses.yaml
  tests/translator/output/error_api_invalid_openapi_path_with_empty_responses.json
  tests/translator/output/error_api_invalid_openapi_path_with_string_responses.json
Labels: pr/internal

#2660 feat: update transform test script to update ManagedPolicyArn with partion
  DEVELOPMENT_GUIDE.md
  bin/add_transform_test.py
Labels: pr/internal

#2671 Convert Relative Paths to Full Paths In Schema
  bin/parse_docs.py
  samtranslator/schema/docs.json
  samtranslator/schema/schema.json
Labels: pr/internal

#2672 fix: schema state machine Policies
  bin/add_transform_test.py
  samtranslator/schema/aws_serverless_statemachine.py
  samtranslator/schema/common.py
  samtranslator/schema/schema.json
  tests/translator/input/schema_validation_1.yaml
  tests/translator/input/schema_validation_2.yaml
  tests/translator/output/aws-cn/schema_validation_1.json
  tests/translator/output/aws-cn/schema_validation_2.json
  tests/translator/output/aws-us-gov/schema_validation_1.json
  tests/translator/output/aws-us-gov/schema_validation_2.json
  tests/translator/output/schema_validation_1.json
  tests/translator/output/schema_validation_2.json
  tests/translator/test_translator.py
Labels: pr/internal

#2673 chore: schema fix and polish
  samtranslator/schema/aws_serverless_api.py
  samtranslator/schema/aws_serverless_function.py
  samtranslator/schema/aws_serverless_httpapi.py
  samtranslator/schema/aws_serverless_statemachine.py
  samtranslator/schema/schema.json
Labels: pr/internal

#2677 chore: more schema tests for invalid Type
  samtranslator/schema/any_cfn_resource.py
  samtranslator/schema/schema.json
  tests/translator/input/schema_validation_3.yaml
  tests/translator/output/aws-cn/schema_validation_3.json
  tests/translator/output/aws-us-gov/schema_validation_3.json
  tests/translator/output/schema_validation_3.json
Labels: pr/internal

#2679 chore: tighter schema type for RestApiId
  samtranslator/schema/aws_serverless_function.py
  samtranslator/schema/common.py
  samtranslator/schema/schema.json
Labels: pr/internal

#2678 chore: Add SnapStart into invalid Global error message
  samtranslator/plugins/globals/globals.py
  tests/translator/output/error_globals_unsupported_property.json
Labels: pr/internal

#2682 chore: Refactor OpenApiEditor and SwaggerEditor to reduce duplicate code
  samtranslator/model/api/api_generator.py
  samtranslator/model/eventsources/push.py
  samtranslator/model/stepfunctions/events.py
  samtranslator/open_api/base_editor.py
  samtranslator/open_api/open_api.py
  samtranslator/plugins/globals/globals.py
  samtranslator/swagger/swagger.py
Labels: pr/internal

#2683 fix: Raise correct exception when path/method items from get_conditional_contents are not dict
  samtranslator/open_api/base_editor.py
  samtranslator/open_api/open_api.py
  samtranslator/swagger/swagger.py
  tests/translator/output/error_http_api_null_method.json
  tests/translator/output/error_invalid_method_definition.json
  tests/translator/output/error_null_method_definition.json
Labels: pr/internal

#2680 Don't strip hyphen from BasePathMapping
  samtranslator/model/api/api_generator.py
  samtranslator/schema/aws_serverless_api.py
  samtranslator/schema/schema.json
  tests/translator/input/api_with_custom_base_path.yaml
  tests/translator/output/api_with_custom_base_path.json
  tests/translator/output/aws-cn/api_with_custom_base_path.json
  tests/translator/output/aws-us-gov/api_with_custom_base_path.json
Labels: pr/internal

#2684 feat: Add RolePath support for AWS::Serverless::StateMachine
  integration/resources/expected/single/state_machine_with_role_path.json
  integration/resources/templates/single/state_machine_with_role_path.yaml
  integration/single/test_basic_state_machine.py
  samtranslator/model/sam_resources.py
  samtranslator/model/stepfunctions/generators.py
  samtranslator/schema/aws_serverless_statemachine.py
  samtranslator/schema/schema.json
  tests/translator/input/state_machine_with_role_path.yaml
  tests/translator/output/aws-cn/state_machine_with_role_path.json
  tests/translator/output/aws-us-gov/state_machine_with_role_path.json
  tests/translator/output/state_machine_with_role_path.json
Labels: pr/internal

#2686 docs: add section about schema changes
  DEVELOPMENT_GUIDE.md
Labels: pr/internal
