Repository aws/serverless-application-model, pull requests merged in 2022-06, with the labels that each got.

#2407 test: Add tests for intrinsics support for DefinitionBody
  tests/translator/input/definition_body_intrinsics_support.yaml
  tests/translator/output/aws-cn/definition_body_intrinsics_support.json
  tests/translator/output/aws-us-gov/definition_body_intrinsics_support.json
  tests/translator/output/definition_body_intrinsics_support.json
  tests/translator/test_translator.py
Labels: pr/internal

#2409 fix: check null method for open api
  samtranslator/open_api/open_api.py
  tests/translator/input/error_http_api_null_method.yaml
  tests/translator/output/error_http_api_null_method.json
Labels: pr/internal

#2411 Release 1.46.0 (to develop)
  samtranslator/__init__.py
Labels: pr/internal

#2339 validate Http Api Authorizers identity Header
  samtranslator/model/apigatewayv2.py
  tests/translator/input/error_api_authorizer_property_indentity_header_with_invalid_type.yaml
  tests/translator/output/error_api_authorizer_property_indentity_header_with_invalid_type.json
Labels: pr/external

#2414 fix: update error message to contain the normalized method rather than the method dict
  samtranslator/open_api/open_api.py
  tests/translator/output/error_http_api_null_method.json
Labels: pr/internal

#2416 fix: use array of exceptions instead of str for InvalidDocumentException
  samtranslator/model/eventsources/push.py
  samtranslator/open_api/open_api.py
  samtranslator/swagger/swagger.py
  tests/translator/output/error_http_api_invalid_openapi.json
Labels: pr/internal

#2413 fix: Allow Implicit HTTP APIs to write when value of method is None
  samtranslator/open_api/open_api.py
  tests/openapi/test_openapi.py
  tests/translator/input/http_api_with_null_path.yaml
  tests/translator/output/aws-cn/function_with_alias_and_code_sha256.json
  tests/translator/output/aws-cn/http_api_with_null_path.json
  tests/translator/output/aws-us-gov/function_with_alias_and_code_sha256.json
  tests/translator/output/aws-us-gov/http_api_with_null_path.json
  tests/translator/output/function_with_alias_and_code_sha256.json
  tests/translator/output/http_api_with_null_path.json
  tests/translator/test_translator.py
Labels: pr/internal

#2422 blogs, video and workshop update in readme
  README.md
Labels: pr/external, stage/needs-triage

#2425 fix: Fail gracefully when AutoPublishAlias is an empty string
  samtranslator/model/sam_resources.py
  tests/translator/input/error_auto_publish_alias_empty_string.yaml
  tests/translator/output/error_auto_publish_alias_empty_string.json
Labels: pr/internal

#2427 chore: [Foss] Sync public: Update region service exclusion list
  integration/config/region_service_exclusion.yaml
  integration/single/test_basic_function.py
Labels: pr/internal

#2434 chore: [Foss] Sync public: Add back hash verification
  integration/resources/expected/combination/api_with_custom_domains_edge.json
  integration/resources/expected/combination/api_with_custom_domains_regional.json
  integration/resources/expected/combination/api_with_custom_domains_regional_ownership_verification.json
  integration/resources/expected/single/basic_api_with_tags.json
Labels: pr/internal

#2437 feat: [Foss] Sync public: remove region service exclusion and inclusion list
  integration/config/region_service_exclusion.yaml
  integration/config/region_service_inclusion.yaml
  integration/helpers/resource.py
Labels: pr/internal

#2436 chore: [Foss] Sync public: Add skip condition for EFS tests
  integration/combination/test_function_with_file_system_config.py
  integration/config/service_names.py
Labels: pr/internal

#2435 fix: [Foss] Sync public: Update custom domain tests resource
  integration/resources/expected/combination/http_api_with_custom_domains_regional_ownership_verification.json
  integration/resources/templates/combination/api_with_custom_domains_regional_ownership_verification.yaml
Labels: pr/internal
