Repository aws/serverless-application-model, pull requests merged in 2022-12, with the labels that each got.

#2691 cr: Run build for all pull requests
  .github/workflows/build.yml
Labels: pr/internal

#2694 Remove PR Labeler Action
  .github/workflows/pr-labeler.yml
Labels: pr/internal

#2749 chore: adding types part 2
  samtranslator/intrinsics/resolver.py
  samtranslator/model/exceptions.py
  samtranslator/model/preferences/deployment_preference_collection.py
  samtranslator/plugins/application/serverless_app_plugin.py
  samtranslator/plugins/sam_plugins.py
  samtranslator/policy_template_processor/processor.py
  samtranslator/policy_template_processor/template.py
  samtranslator/translator/translator.py
Labels: maintainer/need-followup

#2690 Added support for mTLS auth for MSK and Kafka
  samtranslator/model/eventsources/pull.py
  samtranslator/schema/aws_serverless_function.py
  samtranslator/schema/schema.json
  tests/model/eventsources/test_msk_event_source.py
  tests/translator/input/error_msk_invalid_sourceaccessconfigurations.yaml
  tests/translator/input/msk_with_mtls_auth.yaml
  tests/translator/input/self_managed_kafka_with_mtls_auth.yaml
  tests/translator/output/aws-cn/msk_with_mtls_auth.json
  tests/translator/output/aws-cn/self_managed_kafka_with_mtls_auth.json
  tests/translator/output/aws-us-gov/msk_with_mtls_auth.json
  tests/translator/output/aws-us-gov/self_managed_kafka_with_mtls_auth.json
  tests/translator/output/error_msk_invalid_sourceaccessconfigurations.json
  tests/translator/output/msk_with_mtls_auth.json
  tests/translator/output/self_managed_kafka_with_mtls_auth.json
Labels: stage/needs-triage
