Repository aws/serverless-application-model, pull requests merged in 2022-03, with the labels that each got.

#2334 chore: Remove duplicated Docs
  versions/2016-10-31.md
Labels: pr/internal

#2322 validate Lambda Authorizer property identity
  samtranslator/model/apigatewayv2.py
  tests/translator/input/error_api_authorizer_property_indentity_with_invalid_type.yaml
  tests/translator/output/error_api_authorizer_property_indentity_with_invalid_type.json
Labels: pr/external, maintainer/need-response

#2051 chore: update setup.cfg key to use underscore
  setup.cfg
Labels: pr/external, maintainer/need-response

#2343 test: Add retries on flaky integration test
  integration/combination/test_api_with_gateway_responses.py
Labels: pr/internal

#2311 fix: remove py3.6 support and add py3.9 and py3.10
  appveyor-integration-test.yml
  appveyor.yml
  setup.py
  tox.ini
Labels: pr/internal

#2345 Revert "chore: bump version to 1.43.0"
  samtranslator/__init__.py
Labels: pr/internal

#2346 Revert "handle 'Invalid Swagger Document' and refactor some validatio…
  samtranslator/model/api/api_generator.py
  samtranslator/swagger/swagger.py
  tests/model/api/test_api_generator.py
  tests/swagger/test_swagger.py
  tests/translator/input/api_with_resource_refs.yaml
  tests/translator/input/error_api_definition_body_invalid_openapi_version.yaml
  tests/translator/input/error_api_definition_body_invalid_paths.yaml
  tests/translator/input/error_api_definition_body_missing_openapi_or_swagger.yaml
  tests/translator/input/error_api_definition_body_missing_paths.yaml
  tests/translator/input/error_api_invalid_auth.yaml
  tests/translator/input/error_api_invalid_definitionuri.yaml
  tests/translator/input/error_api_invalid_request_model.yaml
  tests/translator/input/explicit_api.yaml
  tests/translator/input/explicit_api_openapi_3.yaml
  tests/translator/output/api_with_resource_refs.json
  tests/translator/output/aws-cn/api_with_resource_refs.json
  tests/translator/output/aws-cn/explicit_api.json
  tests/translator/output/aws-cn/explicit_api_openapi_3.json
  tests/translator/output/aws-us-gov/api_with_resource_refs.json
  tests/translator/output/aws-us-gov/explicit_api.json
  tests/translator/output/aws-us-gov/explicit_api_openapi_3.json
  tests/translator/output/error_api_definition_body_invalid_openapi_version.json
  tests/translator/output/error_api_definition_body_invalid_paths.json
  tests/translator/output/error_api_definition_body_missing_openapi_or_swagger.json
  tests/translator/output/error_api_definition_body_missing_paths.json
  tests/translator/output/error_api_invalid_auth.json
  tests/translator/output/error_api_invalid_request_model.json
  tests/translator/output/explicit_api.json
  tests/translator/output/explicit_api_openapi_3.json
  tests/translator/test_translator.py
Labels: pr/internal

#2347 chore: Version bump to 1.43.0
  samtranslator/__init__.py
Labels: pr/internal

#2340 Validation for API property Model
  samtranslator/model/eventsources/push.py
  tests/translator/input/error_api_with_models_of_invalid_type.yaml
  tests/translator/output/error_api_with_models_of_invalid_type.json
Labels: pr/external, maintainer/need-response

#2223 refactor: Make _get_function_names less verbose
  samtranslator/translator/translator.py
Labels: pr/internal

#2362 Release/v1.44.0 (to main)
  docs/globals.rst
  integration/resources/expected/single/function_with_ephemeral_storage.json
  integration/resources/templates/single/function_with_ephemeral_storage.yaml
  integration/single/test_basic_function.py
  samtranslator/__init__.py
  samtranslator/model/lambda_.py
  samtranslator/model/sam_resources.py
  samtranslator/plugins/globals/globals.py
  tests/translator/input/function_with_ephemeral_storage.yaml
  tests/translator/input/globals_for_function.yaml
  tests/translator/output/aws-cn/function_with_ephemeral_storage.json
  tests/translator/output/aws-cn/globals_for_function.json
  tests/translator/output/aws-us-gov/function_with_ephemeral_storage.json
  tests/translator/output/aws-us-gov/globals_for_function.json
  tests/translator/output/error_globals_unsupported_property.json
  tests/translator/output/function_with_ephemeral_storage.json
  tests/translator/output/globals_for_function.json
  tests/translator/test_translator.py
Labels: pr/internal

#2363 Release/v1.44.0 (to develop)
  docs/globals.rst
  integration/resources/expected/single/function_with_ephemeral_storage.json
  integration/resources/templates/single/function_with_ephemeral_storage.yaml
  integration/single/test_basic_function.py
  samtranslator/__init__.py
  samtranslator/model/lambda_.py
  samtranslator/model/sam_resources.py
  samtranslator/plugins/globals/globals.py
  tests/translator/input/function_with_ephemeral_storage.yaml
  tests/translator/input/globals_for_function.yaml
  tests/translator/output/aws-cn/function_with_ephemeral_storage.json
  tests/translator/output/aws-cn/globals_for_function.json
  tests/translator/output/aws-us-gov/function_with_ephemeral_storage.json
  tests/translator/output/aws-us-gov/globals_for_function.json
  tests/translator/output/error_globals_unsupported_property.json
  tests/translator/output/function_with_ephemeral_storage.json
  tests/translator/output/globals_for_function.json
  tests/translator/test_translator.py
Labels: pr/internal

#2323 Add validation for SecretsManagerKmsKeyId
  samtranslator/model/eventsources/pull.py
  tests/model/eventsources/test_mq_event_source.py
  tests/model/eventsources/test_self_managed_kafka_event_source.py
  tests/translator/input/error_function_with_invalid_kms_type_for_self_managed_kafka.yaml
  tests/translator/input/error_function_with_mq_kms_invalid_type.yaml
  tests/translator/output/error_function_with_invalid_kms_type_for_self_managed_kafka.json
  tests/translator/output/error_function_with_mq_kms_invalid_type.json
Labels: pr/external, maintainer/need-followup

#2365 Bump minimal boto3 version to 1.19.5
  requirements/base.txt
Labels: pr/internal
