Repository aws/serverless-application-model, pull requests merged in 2022-09, with the labels that each got.

#2488 chore: Add basic mypy check (no behavior change)
  Makefile
  mypy.ini
  requirements/dev.txt
  samtranslator/intrinsics/actions.py
  samtranslator/model/__init__.py
  samtranslator/model/api/api_generator.py
  samtranslator/model/api/http_api_generator.py
  samtranslator/model/eventsources/pull.py
  samtranslator/model/eventsources/push.py
  samtranslator/model/sam_resources.py
  samtranslator/model/sqs.py
  samtranslator/model/stepfunctions/events.py
  samtranslator/plugins/globals/globals.py
  samtranslator/public/helpers.py
  samtranslator/sdk/resource.py
  samtranslator/utils/py27hash_fix.py
Labels: pr/internal

#2487 chore: Integration test improvements with ApiKey skips and retry time
  integration/combination/test_api_with_authorizer_apikey.py
  integration/combination/test_api_with_authorizers.py
  integration/combination/test_api_with_gateway_responses.py
  integration/combination/test_api_with_usage_plan.py
  integration/config/service_names.py
  integration/conftest.py
  integration/helpers/base_test.py
Labels: pr/internal

#2490 fix: Update Slack Invite link
  README.md
Labels: pr/internal

#2469 feat: adding support for SSM Parameters (string) as Type
  samtranslator/validator/sam_schema/definitions/parameter.json
  tests/validator/input/root/error_minimal_template_with_parameters.yaml
  tests/validator/input/root/success_minimal_template_with_parameters.yaml
  tests/validator/output/root/error_minimal_template_with_parameters.json
  tests/validator/test_validator_root.py
Labels: pr/external, maintainer/need-followup

#2494 chore: Updated maintainers
  .github/workflows/pr-labeler.yml
Labels: pr/external, stage/needs-triage

#2501 docs: update README
  README.md
Labels: pr/internal

#2497 feat: Add State Property to EventBridgeRule EventSource in Function
  samtranslator/model/eventsources/push.py
  tests/model/eventsources/test_eventbridge_rule_source.py
  tests/translator/input/error_function_with_invalid_event_bridge_rule.yaml
  tests/translator/input/function_with_event_bridge_rule_state.yaml
  tests/translator/output/aws-cn/function_with_event_bridge_rule_state.json
  tests/translator/output/aws-us-gov/function_with_event_bridge_rule_state.json
  tests/translator/output/error_function_with_invalid_event_bridge_rule.json
  tests/translator/output/function_with_event_bridge_rule_state.json
Labels: area/event-source, pr/external, type/new-property, area/event-bridge

#2503 feat: Added UserAttributeUpdateSettings to Cognito
  samtranslator/model/cognito.py
  tests/translator/input/cognito_userpool_with_event.yaml
  tests/translator/output/aws-cn/cognito_userpool_with_event.json
  tests/translator/output/aws-us-gov/cognito_userpool_with_event.json
  tests/translator/output/cognito_userpool_with_event.json
Labels: pr/internal

#2507 chore: Use pre-created SAR app during integration tests
  integration/conftest.py
  integration/helpers/client_provider.py
  integration/resources/templates/single/basic_application_sar_location.yaml
  integration/resources/templates/single/basic_application_sar_location_with_intrinsics.yaml
  integration/setup/example-sar-app.yaml
  integration/setup/test_setup_teardown.py
  integration/single/test_basic_application.py
Labels: pr/internal

#2513 chore: Add test name to request logging and remove default region from pytest.ini
  .gitignore
  Makefile
  integration/combination/test_api_settings.py
  integration/combination/test_api_with_authorizer_apikey.py
  integration/config/logger_configurations.py
  integration/helpers/base_test.py
  integration/single/test_function_with_http_api_and_auth.py
  pytest.ini
Labels: pr/internal

#2514 chore: Only do request logging when internal flag is provided
  integration/combination/test_api_with_authorizers.py
  integration/helpers/base_test.py
Labels: pr/internal

#2517 chore: fix custom domain integration tests for feature toggle
  integration/combination/test_custom_http_api_domains_test.py
  integration/combination/test_custom_rest_api_domains.py
  integration/helpers/base_test.py
  integration/resources/expected/combination/api_with_custom_domains_edge_feature_toggle.json
  integration/resources/expected/combination/api_with_custom_domains_regional_feature_toggle.json
  integration/resources/expected/combination/api_with_custom_domains_regional_ownership_verification_feature_toggle.json
  integration/resources/expected/combination/http_api_with_custom_domains_regional_feature_toggle.json
  integration/resources/expected/combination/http_api_with_custom_domains_regional_ownership_verification_feature_toggle.json
  integration/resources/templates/combination/api_with_custom_domains_edge.yaml
  integration/resources/templates/combination/api_with_custom_domains_regional.yaml
  integration/resources/templates/combination/api_with_custom_domains_regional_ownership_verification.yaml
  integration/resources/templates/combination/http_api_with_custom_domains_regional.yaml
  integration/resources/templates/combination/http_api_with_custom_domains_regional_ownership_verification.yaml
Labels: pr/internal

#2518 Revert "chore: fix custom domain integration tests for feature toggle"
  integration/combination/test_custom_http_api_domains_test.py
  integration/combination/test_custom_rest_api_domains.py
  integration/helpers/base_test.py
  integration/resources/expected/combination/api_with_custom_domains_edge_feature_toggle.json
  integration/resources/expected/combination/api_with_custom_domains_regional_feature_toggle.json
  integration/resources/expected/combination/api_with_custom_domains_regional_ownership_verification_feature_toggle.json
  integration/resources/expected/combination/http_api_with_custom_domains_regional_feature_toggle.json
  integration/resources/expected/combination/http_api_with_custom_domains_regional_ownership_verification_feature_toggle.json
  integration/resources/templates/combination/api_with_custom_domains_edge.yaml
  integration/resources/templates/combination/api_with_custom_domains_regional.yaml
  integration/resources/templates/combination/api_with_custom_domains_regional_ownership_verification.yaml
  integration/resources/templates/combination/http_api_with_custom_domains_regional.yaml
  integration/resources/templates/combination/http_api_with_custom_domains_regional_ownership_verification.yaml
Labels: pr/internal
