Repository aws/serverless-application-model, pull requests merged in 2022-01, with the labels that each got.

#2182 fix: Py27hash fix
  DEVELOPMENT_GUIDE.md
  MANIFEST.in
  Makefile
  THIRD_PARTY_LICENSES
  appveyor-integration-test.yml
  appveyor.yml
  pyproject.toml
  samtranslator/intrinsics/actions.py
  samtranslator/model/api/api_generator.py
  samtranslator/model/apigateway.py
  samtranslator/model/eventsources/push.py
  samtranslator/model/exceptions.py
  samtranslator/open_api/open_api.py
  samtranslator/parser/parser.py
  samtranslator/plugins/api/implicit_api_plugin.py
  samtranslator/swagger/swagger.py
  samtranslator/third_party/__init__.py
  samtranslator/third_party/py27hash/__init__.py
  samtranslator/third_party/py27hash/hash.py
  samtranslator/translator/transform.py
  samtranslator/utils/py27hash_fix.py
  setup.cfg
  setup.py
  tests/translator/input/function_with_null_events.yaml
  tests/translator/input/state_machine_with_null_events.yaml
  tests/translator/output/aws-cn/function_with_null_events.json
  tests/translator/output/aws-cn/state_machine_with_null_events.json
  tests/translator/output/aws-us-gov/function_with_null_events.json
  tests/translator/output/aws-us-gov/state_machine_with_null_events.json
  tests/translator/output/function_with_null_events.json
  tests/translator/output/state_machine_with_null_events.json
  tests/translator/test_translator.py
  tests/utils/test_py27hash_fix.py
  tox.ini
Labels: pr/internal

#2276 chore: bump version to 1.43.0
  samtranslator/__init__.py
Labels: pr/internal

#2286 Update integ test expected result to incorporate py27hashfix changes
  integration/resources/expected/single/basic_api_with_mode_update.json
Labels: pr/internal

#2277 [minor docs] Updates examples link to current non-archived repo
  examples/apps/README.md
Labels: pr/external

#2273 fix: Raise exception if provided Auth.Authorizers.Identity isn't a dict
  samtranslator/model/apigateway.py
  tests/translator/input/error_api_invalid_auth_identity_cognito.yaml
  tests/translator/input/error_api_invalid_auth_identity_lambda_request.yaml
  tests/translator/output/error_api_invalid_auth_identity_cognito.json
  tests/translator/output/error_api_invalid_auth_identity_lambda_request.json
Labels: pr/internal

#1582 fix: Correct CognitoUserPool SmsConfiguration validation type
  samtranslator/model/cognito.py
  samtranslator/parser/parser.py
  tests/translator/input/congito_userpool_with_sms_configuration.yaml
  tests/translator/output/aws-cn/congito_userpool_with_sms_configuration.json
  tests/translator/output/aws-us-gov/congito_userpool_with_sms_configuration.json
  tests/translator/output/congito_userpool_with_sms_configuration.json
  tests/translator/test_translator.py
Labels: blocked/more-info-needed, pr/external, maintainer/need-followup

#2296 fix: accept empty components property in Open Api Definition
  samtranslator/model/api/api_generator.py
  tests/translator/input/api_with_security_definition_and_components.yaml
  tests/translator/input/api_with_security_definition_and_no_components.yaml
  tests/translator/input/api_with_security_definition_and_none_components.yaml
  tests/translator/output/api_with_security_definition_and_components.json
  tests/translator/output/api_with_security_definition_and_no_components.json
  tests/translator/output/api_with_security_definition_and_none_components.json
  tests/translator/output/aws-cn/api_with_security_definition_and_components.json
  tests/translator/output/aws-cn/api_with_security_definition_and_no_components.json
  tests/translator/output/aws-cn/api_with_security_definition_and_none_components.json
  tests/translator/output/aws-us-gov/api_with_security_definition_and_components.json
  tests/translator/output/aws-us-gov/api_with_security_definition_and_no_components.json
  tests/translator/output/aws-us-gov/api_with_security_definition_and_none_components.json
  tests/translator/test_translator.py
Labels: pr/internal

#2170 Corrected gitpod link to open this repo instead of aws-sam-cli
  DEVELOPMENT_GUIDE.md
Labels: pr/external, maintainer/need-response

#2236 docs: updating EventBridgeRule documentation
  versions/2016-10-31.md
Labels: pr/external, maintainer/need-response

#2300 Update INTEGRATION_TESTS.md
  INTEGRATION_TESTS.md
Labels: pr/internal

#2299 Clean up Py2 dependencies and update to use native unittest.mock
  requirements/base.txt
  requirements/dev.txt
  tests/feature_toggle/test_feature_toggle.py
  tests/intrinsics/test_actions.py
  tests/intrinsics/test_resolver.py
  tests/metrics/test_method_decorator.py
  tests/metrics/test_metrics.py
  tests/model/api/test_api_generator.py
  tests/model/api/test_http_api_generator.py
  tests/model/eventsources/test_api_event_source.py
  tests/model/eventsources/test_cloudwatch_event_source.py
  tests/model/eventsources/test_cloudwatchlogs_event_source.py
  tests/model/eventsources/test_eventbridge_rule_source.py
  tests/model/eventsources/test_schedule_event_source.py
  tests/model/eventsources/test_sns_event_source.py
  tests/model/stepfunctions/test_api_event.py
  tests/model/stepfunctions/test_cloudwatchevents_event.py
  tests/model/stepfunctions/test_eventbridge_rule_source.py
  tests/model/stepfunctions/test_schedule_event.py
  tests/model/stepfunctions/test_state_machine_generator.py
  tests/model/test_api_v2.py
  tests/model/test_function_policies.py
  tests/model/test_resource_policies.py
  tests/model/test_sam_resources.py
  tests/parser/test_parser.py
  tests/plugins/api/test_default_definition_body_plugin.py
  tests/plugins/api/test_implicit_api_plugin.py
  tests/plugins/application/test_serverless_app_plugin.py
  tests/plugins/globals/test_globals.py
  tests/plugins/globals/test_globals_plugin.py
  tests/plugins/policies/test_policy_templates_plugin.py
  tests/policy_template_processor/test_processor.py
  tests/policy_template_processor/test_template.py
  tests/sdk/test_parameter.py
  tests/swagger/test_swagger.py
  tests/test_model.py
  tests/test_plugins.py
  tests/translator/model/preferences/test_deployment_preference_collection.py
  tests/translator/test_api_resource.py
  tests/translator/test_arn_generator.py
  tests/translator/test_function_resources.py
  tests/translator/test_logical_id_generator.py
  tests/translator/test_managed_policies_translator.py
  tests/translator/test_resource_level_attributes.py
  tests/translator/test_translator.py
  tests/unit/model/preferences/test_deployment_preference_collection.py
  tests/unit/test_region_configuration.py
  tests/unit/translator/test_arn_generator.py
  tests/utils/test_py27hash_fix.py
Labels: pr/internal

#1937 Add security policy
  versions/2016-10-31.md
Labels: pr/external, maintainer/need-response

#2295 fix: Add handling for OpenApi definition that has tags with invalid format
  samtranslator/open_api/open_api.py
  tests/translator/input/error_http_api_invalid_tags_format.yaml
  tests/translator/output/error_http_api_invalid_tags_format.json
Labels: pr/internal

#2302 Remove six as dependency
  .pylintrc
  requirements/base.txt
  samtranslator/intrinsics/actions.py
  samtranslator/intrinsics/resource_refs.py
  samtranslator/model/__init__.py
  samtranslator/model/api/api_generator.py
  samtranslator/model/api/http_api_generator.py
  samtranslator/model/eventbridge_utils.py
  samtranslator/model/eventsources/pull.py
  samtranslator/model/eventsources/push.py
  samtranslator/model/function_policies.py
  samtranslator/model/resource_policies.py
  samtranslator/model/role_utils/role_constructor.py
  samtranslator/model/s3_utils/uri_parser.py
  samtranslator/model/sam_resources.py
  samtranslator/model/stepfunctions/events.py
  samtranslator/model/stepfunctions/generators.py
  samtranslator/model/types.py
  samtranslator/open_api/open_api.py
  samtranslator/plugins/api/implicit_http_api_plugin.py
  samtranslator/plugins/api/implicit_rest_api_plugin.py
  samtranslator/plugins/globals/globals.py
  samtranslator/swagger/swagger.py
  samtranslator/translator/logical_id_generator.py
  samtranslator/translator/translator.py
  samtranslator/yaml_helper.py
  tests/sdk/test_template.py
Labels: pr/internal

#2303 Fix all warnings in tests
  pytest.ini
  requirements/dev.txt
  samtranslator/intrinsics/actions.py
  samtranslator/metrics/metrics.py
  samtranslator/model/eventsources/push.py
  samtranslator/open_api/open_api.py
Labels: pr/internal

#2285 fix: Raise Invalid Resource When DisableExecuteApiEndpoint: False And Has No DefinitionBody
  bin/sam-translate.py
  samtranslator/model/api/api_generator.py
  samtranslator/model/api/http_api_generator.py
  tests/translator/input/error_api_with_disable_api_execute_endpoint_false.yaml
  tests/translator/input/error_http_api_with_disable_api_execute_endpoint_false.yaml
  tests/translator/output/error_api_with_disable_api_execute_endpoint_false.json
  tests/translator/output/error_http_api_with_disable_api_execute_endpoint_false.json
Labels: pr/internal

#2263 handle 'Invalid Swagger Document' and refactor some validation into Swagger Editor constructor
  samtranslator/model/api/api_generator.py
  samtranslator/swagger/swagger.py
  tests/model/api/test_api_generator.py
  tests/swagger/test_swagger.py
  tests/translator/input/api_with_resource_refs.yaml
  tests/translator/input/error_api_definition_body_invalid_openapi_version.yaml
  tests/translator/input/error_api_definition_body_invalid_paths.yaml
  tests/translator/input/error_api_definition_body_missing_openapi_or_swagger.yaml
  tests/translator/input/error_api_definition_body_missing_paths.yaml
  tests/translator/input/error_api_invalid_auth.yaml
  tests/translator/input/error_api_invalid_definitionuri.yaml
  tests/translator/input/error_api_invalid_request_model.yaml
  tests/translator/input/explicit_api.yaml
  tests/translator/input/explicit_api_openapi_3.yaml
  tests/translator/output/api_with_resource_refs.json
  tests/translator/output/aws-cn/api_with_resource_refs.json
  tests/translator/output/aws-cn/explicit_api.json
  tests/translator/output/aws-cn/explicit_api_openapi_3.json
  tests/translator/output/aws-us-gov/api_with_resource_refs.json
  tests/translator/output/aws-us-gov/explicit_api.json
  tests/translator/output/aws-us-gov/explicit_api_openapi_3.json
  tests/translator/output/error_api_definition_body_invalid_openapi_version.json
  tests/translator/output/error_api_definition_body_invalid_paths.json
  tests/translator/output/error_api_definition_body_missing_openapi_or_swagger.json
  tests/translator/output/error_api_definition_body_missing_paths.json
  tests/translator/output/error_api_invalid_auth.json
  tests/translator/output/error_api_invalid_request_model.json
  tests/translator/output/explicit_api.json
  tests/translator/output/explicit_api_openapi_3.json
  tests/translator/test_translator.py
Labels: pr/internal

#2306 Update PR template to add integration tests in checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr/internal

#2284 Improve exception processing for Route53 with invalid type
  samtranslator/model/api/api_generator.py
  tests/translator/input/error_api_with_custom_domains_route53_invalid_type.yaml
  tests/translator/output/error_api_with_custom_domains_route53_invalid_type.json
Labels: pr/internal
